### PR TITLE
.net core 2.0 and security changes https://github.com/aspnet/Security/issues/1310

### PR DESCRIPTION
**Pull request by SychevIgor**
…/issues/1310

### CODE REVIEW

**Comment by SychevIgor** [comment]
Is this Repo maintained?

**Comment by parakhj** [comment]
Sorry about that! I tried out the changes earlier and everything looked good. Seems like I forgot to follow up here - could you post this to another branch in the repo (maybe call the branch dotnet2.0). We don't want to lose the 1.X sample just yet

**Comment by SychevIgor** [comment]
@parakhj I can't create branch in this repo. If you will create branch, I will can switch branch to merge in a PR.

P.S. maybe we will can do similar thinks for other repos 
https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/pull/19
https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore/pull/10
https://github.com/Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore/pull/6
https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore-v2/pull/8

**Comment by parakhj** [comment]
Done! https://github.com/Azure-Samples/active-directory-b2c-dotnetcore-webapi/tree/dotnetcore2.0

Thanks for updating it :)

**Comment by jmprieur** [comment]
Thanks for the reminder on the other four samples, @SychevIgor : that's on my list for the non-B2C samples.

**Comment by SychevIgor** [comment]
@parakhj changed

**Pull request merged**
